#' Cross-validate runner outcome models
#'
#' Validates the performance of the runner outcome sub-models using stratified 
#' k-fold cross-validation. Out-of-fold predictions are evaluated by calculating 
#' the percentage of deviance explained for each individual model component.
#'
#' @param data_glmer A data frame containing the prepared model covariates and 
#'   outcomes, typically generated by \code{prep_runner_outcome_data}. Must include 
#'   \code{year}, \code{is_po_attempt}, \code{is_po_success}, \code{is_sb_attempt}, 
#'   and \code{is_sb_success}.
#' @param folds Integer. The number of cross-validation folds to generate. Folds 
#'   are stratified by \code{year}. Defaults to \code{5}.
#' @param verbose Logical. If \code{TRUE}, logs fold-by-fold training and 
#'   prediction progress. Defaults to \code{FALSE}.
#'
#' @return A single-row data frame containing the percentage of deviance explained 
#'   (\code{pctdevexp_*}) for the four outcome stages: \code{po_attempt}, 
#'   \code{po_success}, \code{sb_attempt}, and \code{sb_success}.
#'
#' @importFrom dplyr arrange mutate filter summarize select starts_with n
#' @importFrom stats predict weighted.mean
#' @export
validate_runner_outcome_model <- function(data_glmer, folds = 10, verbose = FALSE) {

  pred_cv <- data_glmer |>
    dplyr::arrange(year, sample(1:dplyr::n())) |>   # stratify folds by year
    dplyr::mutate(fold = rep(1:folds, length = dplyr::n())) |>
    dplyr::mutate(
      prob_po_attempt = NA,
      prob_po_success = NA,
      prob_sb_attempt = NA,
      prob_sb_success = NA,
      null_po_attempt = NA,
      null_po_success = NA,
      null_sb_attempt = NA,
      null_sb_success = NA
    )

  for (v in 1:folds) {
    if (verbose) {
      logger::log_info("  Fitting and predicting fold {v}/{folds}")
    }

    fit <- pred_cv |>
      dplyr::filter(fold != v) |>
      pickoffgame::estimate_runner_outcome_model(verbose = verbose)

    pred_cv$prob_po_attempt[pred_cv$fold == v] <- predict(
      object = fit$po_attempt,
      newdata = pred_cv |>
        dplyr::filter(fold == v),
      type = "response",
      allow.new.levels = TRUE
    )
    pred_cv$null_po_attempt[pred_cv$fold == v] <- pred_cv |>
      dplyr::filter(fold != v) |>
      with(mean(is_po_attempt))

    pred_cv$prob_po_success[pred_cv$fold == v] <- predict(
      object = fit$po_success,
      newdata = pred_cv |>
        dplyr::filter(fold == v),
      type = "response",
      allow.new.levels = TRUE
    )
    pred_cv$null_po_success[pred_cv$fold == v] <- pred_cv |>
      dplyr::filter(fold != v, is_po_attempt) |>
      with(mean(is_po_success))

    pred_cv$prob_sb_attempt[pred_cv$fold == v] <- predict(
      object = fit$sb_attempt,
      newdata = pred_cv |>
        dplyr::filter(fold == v),
      type = "response",
      allow.new.levels = TRUE
    )
    pred_cv$null_sb_attempt[pred_cv$fold == v] <- pred_cv |>
      dplyr::filter(fold != v, !is_po_attempt) |>
      with(mean(is_sb_attempt))

    pred_cv$prob_sb_success[pred_cv$fold == v] <- predict(
      object = fit$sb_success,
      newdata = pred_cv |>
        dplyr::filter(fold == v),
      type = "response",
      allow.new.levels = TRUE
    )
    pred_cv$null_sb_success[pred_cv$fold == v] <- pred_cv |>
      dplyr::filter(fold != v, is_sb_attempt) |>
      with(mean(is_sb_success))

    rm(fit)
    gc()
  }

  pct_dev_exp <- pred_cv |>
    dplyr::summarize(
      dev_po_attempt = mean(-2 * log(ifelse(is_po_attempt, prob_po_attempt, 1 - prob_po_attempt))),
      nulldev_po_attempt = mean(
        x = -2 * log(ifelse(is_po_attempt, null_po_attempt, 1 - null_po_attempt))
      ),
      pctdevexp_po_attempt = 1 - dev_po_attempt / nulldev_po_attempt,

      dev_po_success = weighted.mean(
        x = -2 * log(ifelse(is_po_success, prob_po_success, 1 - prob_po_success)),
        w = is_po_attempt
      ),
      nulldev_po_success = weighted.mean(
        x = -2 * log(ifelse(is_po_success, null_po_success, 1 - null_po_success)),
        w = is_po_attempt
      ),
      pctdevexp_po_success = 1 - dev_po_success / nulldev_po_success,

      dev_sb_attempt = weighted.mean(
        x = -2 * log(ifelse(is_sb_attempt, prob_sb_attempt, 1 - prob_sb_attempt)),
        w = !is_po_attempt
      ),
      nulldev_sb_attempt = weighted.mean(
        x = -2 * log(ifelse(is_sb_attempt, null_sb_attempt, 1 - null_sb_attempt)),
        w = !is_po_attempt
      ),
      pctdevexp_sb_attempt = 1 - dev_sb_attempt / nulldev_sb_attempt,

      dev_sb_success = weighted.mean(
        x = -2 * log(ifelse(is_sb_success, prob_sb_success, 1 - prob_sb_success)),
        w = is_sb_attempt
      ),
      nulldev_sb_success = weighted.mean(
        x = -2 * log(ifelse(is_sb_success, null_sb_success, 1 - null_sb_success)),
        w = is_sb_attempt
      ),
      pctdevexp_sb_success = 1 - dev_sb_success / nulldev_sb_success
    ) |>
    dplyr::select(dplyr::starts_with("pctdevexp"))
  
  return(pct_dev_exp)
}
