#' Cross-validate runner outcome models
#'
#' Validates the performance of the runner outcome sub-models using stratified 
#' k-fold cross-validation. Out-of-fold predictions are evaluated by calculating 
#' the percentage of deviance explained for each individual model component.
#'
#' @param data_glmm A data frame containing the prepared model covariates and 
#'   outcomes, typically generated by \code{prep_runner_outcome_data}. Must include 
#'   \code{year}, \code{is_pickoff_attempt}, \code{is_pickoff_success}, \code{is_runner_going},
#'   \code{is_going_interrupt}, and \code{is_stolen_base}.
#' @param folds Integer. The number of cross-validation folds to generate. Folds 
#'   are stratified by \code{year}. Defaults to \code{5}.
#' @param verbose Logical. If \code{TRUE}, logs fold-by-fold training and 
#'   prediction progress. Defaults to \code{FALSE}.
#'
#' @return A single-row data frame containing the percentage of deviance explained 
#'   (\code{pctdevexp_*}) for the four outcome stages: \code{pickoff_attempt}, 
#'   \code{pickoff_success}, \code{runner_going}, \code{going_interrupt}, and \code{stolen_base}.
#'
#' @importFrom dplyr arrange mutate filter summarize select starts_with n
#' @importFrom stats predict weighted.mean
#' @export
validate_runner_outcome_model <- function(data_glmm, folds = 20, verbose = FALSE) {

  pred_cv <- data_glmm |>
    dplyr::arrange(year, sample(1:dplyr::n())) |>   # stratify folds by year
    dplyr::mutate(fold = rep(1:folds, length = dplyr::n())) |>
    dplyr::mutate(
      prob_pickoff_attempt = NA,
      prob_pickoff_success = NA,
      prob_runner_going = NA,
      prob_going_interrupt = NA,
      prob_stolen_base = NA,
      null_pickoff_attempt = NA,
      null_pickoff_success = NA,
      null_runner_going = NA,
      null_going_interrupt = NA,
      null_stolen_base = NA
    )

  for (v in 1:folds) {
    if (verbose) {
      logger::log_info("  Fitting and predicting fold {v}/{folds}")
    }

    fit <- pred_cv |>
      dplyr::filter(fold != v) |>
      pickoffgame::estimate_runner_outcome_model(verbose = verbose)

    pred_cv$prob_pickoff_attempt[pred_cv$fold == v] <- predict(
      object = fit$pickoff_attempt,
      newdata = pred_cv |>
        dplyr::filter(fold == v),
      type = "response",
      allow.new.levels = TRUE
    )
    pred_cv$null_pickoff_attempt[pred_cv$fold == v] <- pred_cv |>
      dplyr::filter(fold != v) |>
      with(mean(is_pickoff_attempt))

    pred_cv$prob_pickoff_success[pred_cv$fold == v] <- predict(
      object = fit$pickoff_success,
      newdata = pred_cv |>
        dplyr::filter(fold == v),
      type = "response",
      allow.new.levels = TRUE
    )
    pred_cv$null_pickoff_success[pred_cv$fold == v] <- pred_cv |>
      dplyr::filter(fold != v, is_pickoff_attempt) |>
      with(mean(is_pickoff_success))

    pred_cv$prob_runner_going[pred_cv$fold == v] <- predict(
      object = fit$runner_going,
      newdata = pred_cv |>
        dplyr::filter(fold == v),
      type = "response",
      allow.new.levels = TRUE
    )
    pred_cv$null_runner_going[pred_cv$fold == v] <- pred_cv |>
      dplyr::filter(fold != v, !is_pickoff_attempt) |>
      with(mean(is_runner_going))
    
    pred_cv$prob_going_interrupt[pred_cv$fold == v] <- predict(
      object = fit$going_interrupt,
      newdata = pred_cv |>
        dplyr::filter(fold == v),
      type = "response",
      allow.new.levels = TRUE
    )
    pred_cv$null_going_interrupt[pred_cv$fold == v] <- pred_cv |>
      dplyr::filter(fold != v, is_runner_going) |>
      with(mean(is_going_interrupt))

    pred_cv$prob_stolen_base[pred_cv$fold == v] <- predict(
      object = fit$stolen_base,
      newdata = pred_cv |>
        dplyr::filter(fold == v),
      type = "response",
      allow.new.levels = TRUE
    )
    pred_cv$null_stolen_base[pred_cv$fold == v] <- pred_cv |>
      dplyr::filter(fold != v, is_runner_going, !is_going_interrupt) |>
      with(mean(is_stolen_base))

    rm(fit)
    gc()
  }

  pct_dev_exp <- pred_cv |>
    dplyr::summarize(
      dev_pickoff_attempt = mean(-2 * log(ifelse(is_pickoff_attempt, prob_pickoff_attempt, 1 - prob_pickoff_attempt))),
      nulldev_pickoff_attempt = mean(
        x = -2 * log(ifelse(is_pickoff_attempt, null_pickoff_attempt, 1 - null_pickoff_attempt))
      ),
      pctdevexp_pickoff_attempt = 1 - dev_pickoff_attempt / nulldev_pickoff_attempt,

      dev_pickoff_success = weighted.mean(
        x = -2 * log(ifelse(is_pickoff_success, prob_pickoff_success, 1 - prob_pickoff_success)),
        w = is_pickoff_attempt
      ),
      nulldev_pickoff_success = weighted.mean(
        x = -2 * log(ifelse(is_pickoff_success, null_pickoff_success, 1 - null_pickoff_success)),
        w = is_pickoff_attempt
      ),
      pctdevexp_pickoff_success = 1 - dev_pickoff_success / nulldev_pickoff_success,

      dev_runner_going = weighted.mean(
        x = -2 * log(ifelse(is_runner_going, prob_runner_going, 1 - prob_runner_going)),
        w = !is_pickoff_attempt
      ),
      nulldev_runner_going = weighted.mean(
        x = -2 * log(ifelse(is_runner_going, null_runner_going, 1 - null_runner_going)),
        w = !is_pickoff_attempt
      ),
      pctdevexp_runner_going = 1 - dev_runner_going / nulldev_runner_going,

      dev_going_interrupt = weighted.mean(
        x = -2 * log(ifelse(is_going_interrupt, prob_going_interrupt, 1 - prob_going_interrupt)),
        w = is_runner_going
      ),
      nulldev_going_interrupt = weighted.mean(
        x = -2 * log(ifelse(is_going_interrupt, null_going_interrupt, 1 - null_going_interrupt)),
        w = is_runner_going
      ),
      pctdevexp_going_interrupt = 1 - dev_going_interrupt / nulldev_going_interrupt,

      dev_stolen_base = weighted.mean(
        x = -2 * log(ifelse(is_stolen_base, prob_stolen_base, 1 - prob_stolen_base)),
        w = is_runner_going & !is_going_interrupt
      ),
      nulldev_stolen_base = weighted.mean(
        x = -2 * log(ifelse(is_stolen_base, null_stolen_base, 1 - null_stolen_base)),
        w = is_runner_going & !is_going_interrupt
      ),
      pctdevexp_stolen_base = 1 - dev_stolen_base / nulldev_stolen_base
    ) |>
    dplyr::select(dplyr::starts_with("pctdevexp"))
  
  return(pct_dev_exp)
}
